### PR TITLE
Added overall summary doc

### PR DESCRIPTION
**Pull request by gendal**
Added a summary/intro doc, based on the ecosystem paper, which also signposts other relevant docs in the repo

### CODE REVIEW

**Review by petermunnings — APPROVED** [review]
This is a great summary.  We are preparing a PR which will have some additional useful links which I will add to this doc once it is approved.

**Comment by gendal** [comment]
Thanks @petermunnings.  (And thank you to @MarkOldfield who drafted most of the doc, curated in part from an earlier Adhara/R3 doc)

**Comment by gendal** [comment]
interesting... @petermunnings - you don't seem to be in the harmonia-committers group? @MarkOldfield @r3domfox @fenryka - can one of you approve so this gets merged please?

**Review by MarkOldfield — APPROVED** [review]

**Review by fenryka — COMMENTED** [review]
LGTM!

**Comment by ryjones** [comment]
@petermunnings [please accept your pending invitation.](https://github.com/hyperledger-labs)

**Pull request merged**
